# ============================================================
#  Setup-Aliases.ps1 - PowerShell Profile Alias Setup
#  Run as Administrator ONCE to configure all script shortcuts
#
#  UPDATE $scriptsPath below to wherever you saved the scripts
# ============================================================

Write-Host "`n=== Setting up PowerShell Aliases ===" -ForegroundColor Cyan

# UPDATE THIS PATH before running
$scriptsPath = "C:\Users\YOUR_USERNAME\Documents\PowerShell Scripts"

if (-not (Test-Path $scriptsPath)) {
    Write-Host "ERROR: Scripts folder not found at: $scriptsPath" -ForegroundColor Red
    Write-Host "Update the path at the top of this script and re-run." -ForegroundColor Yellow
    exit
}

Write-Host "Clearing existing profile and rewriting clean..." -ForegroundColor Yellow

$profileContent = @"
# ============================================================
# IT Toolkit Script Aliases
# Generated by Setup-Aliases.ps1 — re-run to update
# ============================================================

function morning         { & "$scriptsPath\MorningStartup.ps1" }
function speedboost      { & "$scriptsPath\SpeedBoost.ps1" }
function netdiag         { & "$scriptsPath\NetDiag.ps1" }
function netreset        { & "$scriptsPath\NetReset.ps1" }
function netmonitor      { & "$scriptsPath\NetMonitor.ps1" }
function wifireport      { & "$scriptsPath\WiFiReport.ps1" }
function proxychecker    { & "$scriptsPath\ProxyChecker.ps1" }
function vpnrepair       { & "$scriptsPath\VPNRepair.ps1" }
function printerdiag     { & "$scriptsPath\PrinterDiag.ps1" }
function spoolerreset    { & "$scriptsPath\PrintSpoolerReset.ps1" }
function profilediag     { & "$scriptsPath\UserProfileDiag.ps1" }
function updatefix       { & "$scriptsPath\WindowsUpdateFix.ps1" }
function diskcleanup     { & "$scriptsPath\DiskCleanup.ps1" }
function crashdiag       { & "$scriptsPath\AppCrashDiag.ps1" }
function rdpfix          { & "$scriptsPath\RemoteDesktopFix.ps1" }
function outlookfix      { & "$scriptsPath\OutlookRepair.ps1" }
function slackfix        { & "$scriptsPath\SlackRepair.ps1" }
function browserfix      { & "$scriptsPath\BrowserRepair.ps1" }
function galmanager      { & "$scriptsPath\GALManager.ps1" }
function mapdrives       { & "$scriptsPath\MapDrives.ps1" }
function removechrome    { & "$scriptsPath\RemoveChrome.ps1" }
function reinstallchrome { & "$scriptsPath\ReinstallChrome.ps1" }

function scripts {
    Write-Host "" 
    Write-Host "=== IT Toolkit Commands ===" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  MORNING ROUTINE" -ForegroundColor Yellow
    Write-Host "  morning          - Daily reset and health check" -ForegroundColor White
    Write-Host ""
    Write-Host "  PERFORMANCE" -ForegroundColor Yellow
    Write-Host "  speedboost       - Clear temp files, flush DNS, high performance mode" -ForegroundColor White
    Write-Host "  diskcleanup      - Deep disk cleanup" -ForegroundColor White
    Write-Host ""
    Write-Host "  NETWORK" -ForegroundColor Yellow
    Write-Host "  netdiag          - Full network diagnostic" -ForegroundColor White
    Write-Host "  netreset         - Reset full network stack" -ForegroundColor White
    Write-Host "  netmonitor       - Live connection monitor" -ForegroundColor White
    Write-Host "  wifireport       - Wi-Fi health check" -ForegroundColor White
    Write-Host "  proxychecker     - Proxy and DNS audit" -ForegroundColor White
    Write-Host ""
    Write-Host "  VPN" -ForegroundColor Yellow
    Write-Host "  vpnrepair        - Cisco Secure Client diagnostic and fix" -ForegroundColor White
    Write-Host ""
    Write-Host "  PRINTERS" -ForegroundColor Yellow
    Write-Host "  printerdiag      - Printer status check" -ForegroundColor White
    Write-Host "  spoolerreset     - Clear stuck queue and restart spooler" -ForegroundColor White
    Write-Host ""
    Write-Host "  APPS" -ForegroundColor Yellow
    Write-Host "  outlookfix       - Outlook cache clear and repair" -ForegroundColor White
    Write-Host "  slackfix         - Slack cache clear and repair" -ForegroundColor White
    Write-Host "  browserfix       - Browser repair (Chrome/Edge/Firefox)" -ForegroundColor White
    Write-Host ""
    Write-Host "  SYSTEM" -ForegroundColor Yellow
    Write-Host "  updatefix        - Fix stuck Windows Updates" -ForegroundColor White
    Write-Host "  crashdiag        - App crash and Event Log diagnostic" -ForegroundColor White
    Write-Host "  profilediag      - User profile corruption check" -ForegroundColor White
    Write-Host "  rdpfix           - Enable and fix Remote Desktop" -ForegroundColor White
    Write-Host ""
    Write-Host "  EXCHANGE / GAL" -ForegroundColor Yellow
    Write-Host "  galmanager       - Hide/show/update users in Global Address List" -ForegroundColor White
    Write-Host ""
    Write-Host "  DRIVES" -ForegroundColor Yellow
    Write-Host "  mapdrives        - Map network drives" -ForegroundColor White
    Write-Host ""
    Write-Host "  CHROME" -ForegroundColor Yellow
    Write-Host "  removechrome     - Completely remove Chrome" -ForegroundColor White
    Write-Host "  reinstallchrome  - Reinstall Chrome keeping user data" -ForegroundColor White
    Write-Host ""
    Write-Host "  Type 'scripts' anytime to see this list." -ForegroundColor Gray
    Write-Host ""
}
"@

$profileDir = Split-Path $PROFILE -Parent
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

Set-Content -Path $PROFILE -Value $profileContent -Encoding UTF8
Write-Host "Profile written to: $PROFILE" -ForegroundColor Green

. $PROFILE
Write-Host "Aliases loaded and ready!" -ForegroundColor Green
Write-Host "Type 'scripts' to see all available commands." -ForegroundColor Cyan
Write-Host "`n=== Setup Complete ===" -ForegroundColor Cyan
